-- JOINS --
CREATE DATABASE TESTDB;
USE TESTDB;

SELECT * FROM TABLE1;
CREATE TABLE TABLE1( ID INT, VALUE VARCHAR(10));

-- UNION
-- SELECT 1 AS 'NUMBER', 'RED' AS 'COLOR'
SELECT 1 , 'RED'
UNION
SELECT 2, 'GREEN'
UNION
SELECT 3, 'RED';

SELECT 3, 'RED'
UNION
SELECT 1 , 'RED'
UNION
SELECT 2, 'GREEN';


SELECT 3 AS 'NUMBER', 'RED' AS 'COLOR CHOICE'
UNION
SELECT 1 , 'RED'
UNION
SELECT 2, 'GREEN';

USE SAKILA;
SELECT actor_id, LAST_NAME, last_update FROM ACTOR
UNION
SELECT ADDRESS, district FROM address;
-- INSERT VALUES INT TABLE1
INSERT INTO TABLE1 VALUES(1, 'RED');
SELECT * FROM TABLE1;
DELETE FROM TABLE1;

INSERT INTO TABLE1 (ID, VALUE)
SELECT 1 , 'RED'
UNION
SELECT 2, 'GREEN'
UNION
SELECT 3, 'RED';

CREATE TABLE TABLE2( ID INT, VALUE VARCHAR(10));
INSERT INTO TABLE2 (ID, VALUE)
SELECT 2 , 'BASKET'
UNION
SELECT 3, 'BASE'
UNION
SELECT 6, 'CRICKET'
UNION
SELECT 7, 'FOOT';
SELECT * FROM TABLE2;

SELECT * FROM TABLE1
UNION
SELECT * FROM TABLE2;

-- CROSS JOIN
SELECT * FROM TABLE1
                  CROSS JOIN TABLE2;

-- INNER JOIN
SELECT * FROM TABLE1
                  INNER JOIN TABLE2
                             ON TABLE1.ID = TABLE2.ID;
-- THE INNER KEYWORD IS OPTIONAL
SELECT * FROM TABLE1
                  JOIN TABLE2
                       ON TABLE1.ID = TABLE2.ID;

-- LEFT OUTER JOIN
SELECT * FROM TABLE1
                  LEFT JOIN TABLE2
                            ON TABLE1.ID = TABLE2.ID;

SELECT * FROM TABLE1
                  LEFT OUTER JOIN TABLE2
                                  ON TABLE1.ID = TABLE2.ID;

-- RIGHT OUTER JOIN
SELECT  * FROM TABLE1
                   LEFT OUTER JOIN TABLE2
                                    ON TABLE1.ID = TABLE2.ID;

SELECT  * FROM TABLE1
                   RIGHT JOIN TABLE2
                              ON TABLE1.ID = TABLE2.ID;

-- USING TABLE ALIAS
SELECT  * FROM TABLE1 LT
                   RIGHT OUTER JOIN TABLE2 RT
                                    ON LT.ID = RT.ID;

-- IP
-- FULL OTUER JOIN
-- MATCHING RECORDS (LEFT TABLE + RIGTH TABLE), ALL RECORDS FROM THE LEFT AND RIGHT TABLES.
-- THE RESULT OF INNER JOIN, LEFT OUTER JOIN AND RIGHT OUTER JOIN.
-- TRY OTHER WAYS TO CREATE JOINS

SELECT  * FROM TABLE1
                   LEFT JOIN TABLE2
                       ON TABLE1.ID = TABLE2.ID
UNION
SELECT  * FROM TABLE1 LT
                   RIGHT OUTER JOIN TABLE2 RT
                                    ON LT.ID = RT.ID;